all:
	go build *.go
svr0:
	go run *.go -type=server -id=0
svr1:
	go run *.go -type=server -id=1
svr2:
	go run *.go -type=server -id=2
clt0:
	go run *.go -type=client -id=0
clt1:
	go run *.go -type=client -id=1
clear:
	rm client